/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veriyapilari;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author behlul
 * @param <T>
 */
public class hesaplama<T> extends javax.swing.JFrame {

    DefaultComboBoxModel dcm;
    BufferedReader input = null;
    File file;
    LinkedList equation1;
    LinkedList equation2;
    int x;

    /**
     * Creates new form hesaplama
     */
    public hesaplama() {
        initComponents();
        equation1 = new LinkedList();
        equation2 = new LinkedList();
        dcm = new DefaultComboBoxModel();
        dcm.addElement("+");
        dcm.addElement("-");
        dcm.addElement("*");
        dcm.addElement("/");
        cmbIslemler.setModel(dcm);
        cmbIslemler.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDosyaOku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDenklemler = new javax.swing.JTextArea();
        lblDenklemler = new javax.swing.JLabel();
        btnHesapla = new javax.swing.JButton();
        cmbIslemler = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDosyaOku.setText("DOSYA OKU");
        btnDosyaOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosyaOkuActionPerformed(evt);
            }
        });

        txtDenklemler.setColumns(20);
        txtDenklemler.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtDenklemler.setRows(5);
        jScrollPane1.setViewportView(txtDenklemler);

        lblDenklemler.setText("Denklemler:");

        btnHesapla.setText("HESAPLA");
        btnHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHesaplaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnDosyaOku))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDenklemler)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(cmbIslemler, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHesapla)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnDosyaOku, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblDenklemler)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHesapla)
                    .addComponent(cmbIslemler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDosyaOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosyaOkuActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        int result = jFileChooser.showOpenDialog(this);
        try {
            file = jFileChooser.getSelectedFile();
            if (file != null) {
                input = new BufferedReader(new FileReader(file));
                String equation;
                int count = 0;
                while ((equation = input.readLine()) != null) {
                    switch (count) {
                        case 0:
                            txtDenklemler.setText(txtDenklemler.getText() + equation + "\n");
                            String[] terms = equation.split("\\+|(?=\\-)");
                            for (String term : terms) {
                                if (term.contains("x^")) {
                                    equation1.addLast(Integer.parseInt(term.split("x\\^")[0]), Integer.parseInt(term.split("x\\^")[1]));
                                } else if (!term.contains("x")) {
                                    equation1.addLast(0, Integer.parseInt(term));
                                } else if (term.contains("x") && !term.contains("^")) {
                                    equation1.addLast(Integer.parseInt(term.split("x")[0]), 1);
                                }
                            }
                            break;
                        case 1:
                            txtDenklemler.setText(txtDenklemler.getText() + equation + "\n");
                            terms = equation.split("\\+|(?=\\-)");
                            for (String term : terms) {
                                if (term.contains("x^")) {
                                    equation2.addLast(Integer.parseInt(term.split("x\\^")[0]), Integer.parseInt(term.split("x\\^")[1]));
                                } else if (!term.contains("x")) {
                                    equation2.addLast(0, Integer.parseInt(term));
                                } else if (term.contains("x") && !term.contains("^")) {
                                    equation2.addLast(Integer.parseInt(term.split("x")[0]), 1);
                                }
                            }
                            break;
                        case 2:
                            x = Integer.parseInt(equation);
                    }
                    count++;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Dosya okunamadı. Tekrar deneyiniz.");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(hesaplama.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(hesaplama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDosyaOkuActionPerformed

    private void btnHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHesaplaActionPerformed
        // TODO add your handling code here:
        Node temp1 = equation1.head;;
        Node temp2 = equation2.head;
        LinkedList newEquation = new LinkedList();

//        for (int i = 0; i < equation1.getSize(); i++) {
//            
//            for (int j = 0; j < equation2.getSize(); j++) {
//                
//                if (temp1.data2 == temp2.data2) {
//                    newEquation.addLast((int) temp1.data1 + (int) temp2.data1, temp2.data2);
//                    equation1.remove(temp1.data1, temp1.data2);
//                    equation2.remove(temp2.data1, temp2.data2);
//                }
//                if (temp1.data1.equals(0) && temp2.data1.equals(0)) {
//                    newEquation.addLast(0,(int)temp1.data2+(int)temp2.data2);
//                    equation1.remove(temp1.data1, temp1.data2);
//                    equation2.remove(temp2.data1, temp2.data2);
//                }
//                temp2 = temp2.next;
//            }
//            temp1 = temp1.next;
//            temp2 = equation2.head;
//        }
//        Node temp3 = equation2.head;
//        for (int i = 0; i < equation2.getSize(); i++) {
//            newEquation.addLast(temp3.data1, temp3.data2);
//            temp3 = temp3.next;
//        }
//        temp3 = equation1.head;
//        for (int i = 0; i < equation1.getSize(); i++) {
//            newEquation.addLast(temp3.data1, temp3.data2);
//            temp3 = temp3.next;
//        }
        for (int i = 0; i < equation2.getSize(); i++) {
            equation1.addLast(temp2.data1, temp2.data2);
        }
        equation1.print();
        temp1 = equation1.head;
        for (int i = 0; i < equation1.getSize(); i++) {
            temp2 = equation1.head;
            for (int j = 0; j < equation1.getSize(); j++) {
                if (temp1.data2 == temp2.data2) {
                    newEquation.addLast((int) temp1.data1 + (int) temp2.data1, temp2.data2);
                    equation1.remove(temp1.data1, temp1.data2);
                }
                if (temp1.data1.equals(0) && temp2.data1.equals(0)) {
                    newEquation.addLast(0, (int) temp1.data2 + (int) temp2.data2);
                    equation1.remove(temp1.data1, temp1.data2);
                }
                temp2 = temp2.next;
            }
            temp1 = temp1.next;
        }
        newEquation.print();
    }//GEN-LAST:event_btnHesaplaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hesaplama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDosyaOku;
    private javax.swing.JButton btnHesapla;
    private javax.swing.JComboBox<String> cmbIslemler;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDenklemler;
    private javax.swing.JTextArea txtDenklemler;
    // End of variables declaration//GEN-END:variables
}
